### ISSUE TITLE
Test hard BDA models from LW

### ISSUE THREAD

**Issue by mhtess** [mhtess/psych201s#3]
And document:
- inference algorithm and options that works
- notes

**Comment by hawkrobe** [comment]
To-do list to keep track:
- [x] Chapter 3
- [x] Chapter 4
  - IQ model in 4.3 needs to be cleaned up with `observe`-like primitives instead of `sum(map(...))`
  - exercise 4.3.3 (using incremental MH with gaussian prior and tight data set) gives a wonky posterior for `mu3` -- scores are probably so low in the long tale that every proposal gets rejected. 
- [x] Chapter 6
